---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
spec:
  ports:
  - nodePort: 30081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
  sessionAffinity: None
  type: LoadBalancer
#status:
  #loadBalancer: {}
